src_list:
  - OL

tgt_list:
  - REGIS_DIM


SB:
  mysql_conf:
    database: sahadb.TRANSACTIONSYNC
    dbtable: TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from sahadb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: school
    collection: students


s3_conf:
  s3_bucket: saha-bigdata
  staging_loc: staging


redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

spark_sql_demo:
  agg_demo: >
    select
        AccountNumber,
        UniqueTransactionDescriptions,
        sort_array(UniqueTransactionDescriptions, false) as OrderedUniqueTransactionDescriptions,
        size(UniqueTransactionDescriptions) as CountOfUniqueTransactionTypes,
        array_contains(UniqueTransactionDescriptions, 'Movies') as WentToMovies
    from
        agg_finances
  case_when_demo: >
    select
        company,
        employee.firstName as firstName,
        case
            when company = 'FamilyCo' then 'Premium'
            when company = 'OldCo' then 'Legacy'
            else 'Standard'
        end as Tier
    from
        employees